### ISSUE TITLE
Feedback and sharing mechanism for Content (Article)

### ISSUE THREAD

**Issue by miaeowx** [tjmonsi/nice-v1#46]
Sharing: facebook, twitter, send as 
Erratum: no Feedback as I saw there's already a feedback in other cards

**Comment by tjmonsi** [comment]
@miaeowx please see pages, articles, and data now

**Comment by miaeowx** [comment]
@tjmonsi 
"Feedback has been sent. Thank you for your feedback."  after sending feedback. 

Upon checking in the Dashboard, feedback does not appear.

**Comment by tjmonsi** [comment]
Will work on it tonight

**Comment by tjmonsi** [comment]
@miaeowx can you check the feedback list?

**Comment by miaeowx** [comment]
@tjmonsi Wala pa rin tj. doesn't appear on the feedback < Dashboard.

**Comment by miaeowx** [comment]
@tjmonsi both safari and chrome, nothing is showing.

**Comment by tjmonsi** [comment]
I just deployed it now. Sorry. Can you check again?

**Comment by miaeowx** [comment]
Cleared.
