### ISSUE TITLE
Homepage: Content (Features) display

### ISSUE THREAD

**Issue by miaeowx** [tjmonsi/nice-v1#48]
1. Coding like <br> used in the article shows up in the homepage. 
2. Article title must be completely shown. Should not be cut short by ellipsis.

**Comment by tjmonsi** [comment]
@miaeowx I don't get yung number 1

**Comment by tjmonsi** [comment]
I fixed 2

**Comment by tjmonsi** [comment]
is this ok with you? @miaeowx

**Comment by miaeowx** [comment]
Yes, the content display is fixed now. Thank you. @tjmonsi
